# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cac37cbc31dc99c5b52b749ff1fa7b4323e8f584176552c0510068a593f11ec6ab45f98cb56464f36a07a73bfa9f4f5838399960f9e996f82a1b2c15f4973db
  twitter_key: 591c141f69d498f35e7e0ea6efe0f06971f189988ae4a17d73ebefe1cb59c579ac94632fd008a19aa49d9330b3ce4c0506ad89789b6bb933af76d26fe44bd863 #dummy
  twitter_secret: e2bd2feaede8f1d03d524e2036e2f4cec0f7a3b77a7ff51c2f06e0221da67d4d79a5366a473d71280592e4e8c7cbdc9fef2061cc5409ab4e464d74eab558b8bd #dummy
  github_key: 8f17197c8193871ca1db
  github_secret: 69958e21e76d07a89fb855d18fe2b6539df6a0d5
  facebook_key: 1fc9d4633d3d903cd5c99d443b4e02330605c2ccd3357ca73730f8e4ca7eac31811328da6c8fa19d35e6af4f629c7550aa83ec7436c8f985922c1942bafb9b2c #dummy
  facebook_secret: 4fdd54c191e5fa1ceef7554fe55f4037cff2ca884824a8e15fc7c6be421fa630207a35c09776bc9bdf580b37b9cc744a1dd2923ec87284e55849abcee5192dfb #dummy

test:
  secret_key_base: 478092cd7e6d88e06df69a173c42119ba70a89294086cbbdc8ab9ae3ae17e1dc8db3f658fb86253d3084ccb8cc739e4d4e80fb9c0f4f96e0a8604dd505447c7c
  twitter_key: testtwitterkey
  twitter_secret: testtwittersecret
  github_key: testgithubkey
  github_secret: testgithubsecret
  facebook_key: testfacebookkey
  facebook_secret: testfacebooksecret

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_key: <%= ENV["TWITTER_KEY"] %>
  twitter_secret: <%= ENV["TWITTER_SECRET"] %>
  github_key: <%= ENV["GITHUB_KEY"] %>
  github_secret: <%= ENV["GITHUB_SECRET"] %>
  facebook_key: <%= ENV["FACEBOOK_KEY"] %>
  facebook_secret: <%= ENV["FACEBOOK_SECRET"] %>
